server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: FrontUI
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
  security:
    filter:
      dispatcher-types: REQUEST, ASYNC, ERROR
    ignore:
      - /static/**
      - /public/**
      - /resources/**
      - /webjars/**
accounts:
  service:
    url: http://accounts-service:8082
logging:
  level:
    root: INFO
  org:
    springframework: DEBUG
    boot: DEBUG



