server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: service-frontui
  config:
    import: "consul:"  # Add a spring.config.import=consul: property to your configuration.
  cloud:
    consul:
      host: consul          # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)
      discovery:
        service-name: service-frontui  # Необязательно, по умолчанию берётся spring.application.name
        health-check-path: /actuator/health
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        data-key: data
        format: PROPERTIES
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
  security:
    oauth2:
      client:
        registration:
          frontui-client:
            provider: spring
            client-id: frontui-service
            client-secret: frontui-secret
            authorization-grant-type: client_credentials
            scope: frontui
        provider:
          spring:
            token-uri: http://auth-service:9000/oauth2/token
    filter:
      dispatcher-types: REQUEST, ASYNC, ERROR
    ignore:
      - /static/**
      - /public/**
      - /resources/**
      - /webjars/**
service:
  url:
    gateway: TEST #http://service-accounts # http://accounts-service:8082
    # cash: TEST #http://service-cash # http://cash-service:8083
    # exchangegenerator: http://service-exchange-generator # http://exchange-generator-service:8086
    # exchange: TEST #http://service-exchange # http://exchange-service:8085
    # transfer: TEST #http://service-transfer # http://transfer-service:8084
    # notifications: TEST #http://service-notifications # http://notifications-service:8088
client:
  registration:
    id: "frontui-client"
logging:
  level:
    root: INFO
    ru.mityunin: INFO
  org:
    springframework: DEBUG
    boot: DEBUG



