server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: FrontUI
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
  security:
    filter:
      dispatcher-types: REQUEST, ASYNC, ERROR
    ignore:
      - /static/**
      - /public/**
      - /resources/**
      - /webjars/**
service:
  accounts:
    url: http://accounts-service:8082
  cash:
    url: http://cash-service:8083
  exchangegenerator:
    url: http://exchange-generator-service:8086
  exchange:
    url: http://exchange-service:8085
  transfer:
    url: http://transfer-service:8084
logging:
  level:
    root: INFO
    ru.mityunin: INFO
  org:
    springframework: DEBUG
    boot: DEBUG



