server:
  port: ${SERVER_PORT:8086}
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: ExchangeGenerator
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: exchange_generator
        format_sql: true
        hbm2ddl.schema-generation.scripts.action: create
        hbm2ddl.schema-generation.scripts.create-target: init.sql
        hbm2ddl.schema-generation.scripts.create-source: metadata