server:
  port: ${SERVER_PORT:8082}
spring:
  application:
    name: Accounts
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: accounts
        format_sql: true
        hbm2ddl.schema-generation.scripts.action: create
        hbm2ddl.schema-generation.scripts.create-target: init.sql
        hbm2ddl.schema-generation.scripts.create-source: metadata
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
service:
  url:
    notifications: http://notifications-service:8088

logging:
  level:
    root: INFO
  org:
    springframework: DEBUG
    boot: DEBUG