spring:
  cloud:
    consul:
      enabled: false  # Полностью отключаем Consul
      discovery:
        enabled: false
      config:
        enabled: false
    config:
      import: ""

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: accounts
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  # URL для тестов
service:
  url:
    gateway: "http://localhost:8080"
  api:
    notifications: ""

security:
  oauth2:
    enabled: false

resilience4j:
  enabled: false