server:
  port: ${SERVER_PORT:8082}
spring:
  application:
    name: Accounts
  config:
    import: "consul:" # Add a spring.config.import=consul: property to your configuration.
  cloud:
    consul:
      host: consul          # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)
      discovery:
        service-name: service-accounts  # Необязательно, по умолчанию берётся spring.application.name
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: accounts
        format_sql: true
        hbm2ddl.schema-generation.scripts.action: create
        hbm2ddl.schema-generation.scripts.create-target: init.sql
        hbm2ddl.schema-generation.scripts.create-source: metadata
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
service:
  url:
    notifications: http://service-notifications # http://notifications-service:8088

logging:
  level:
    root: INFO
  org:
    springframework: DEBUG
    boot: DEBUG