server:
  port: ${SERVER_PORT:8085}
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: service-exchange
  config:
    import: "consul:"  # Add a spring.config.import=consul: property to your configuration.
  cloud:
    consul:
      host: consul          # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)
      discovery:
        service-name: service-exchange  # Необязательно, по умолчанию берётся spring.application.name
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        data-key: data
        format: PROPERTIES
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию
  security:
    oauth2:
      client:
        registration:
          exchange-client:
            provider: spring
            client-id: exchange-service
            client-secret: exchange-secret
            authorization-grant-type: client_credentials
            scope: exchange
        provider:
          spring:
            token-uri: http://auth-service:9000/oauth2/token
service:
  url:
    gateway: TEST # http://service-exchange-generator # http://exchange-generator-service:8086
client:
  registration:
    id: "exchange-client"