server:
  port: ${SERVER_PORT:8085}
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: Exchange
service:
  url:
    exchangegenerator: http://exchange-generator-service:8086